[predicates]
executable = "{*,**,*/,**/}starsector.sh"

[manifest]
title = "Starsector"

[vars]
root = "$HOME/.local/share"

[about]
name = "Starsector local"
desc = "Starsector when installed locally into a directory"
